### ISSUE TITLE
Imports broken due to expired TLS certificate

### ISSUE THREAD

**Issue by rubenv** [trimmer-io/go-xmp#5]
> Websites prove their identity via certificates, which are valid for a set time period. The certificate for trimmer.io expired on 8/17/2020.
>
> Error code: SEC_ERROR_EXPIRED_CERTIFICATE

Please don't use vanity imports unless there's a really good reason.

**Comment by echa** [comment]
Thanks, fixed. LetsEncrypt cert didn't auto-renew. The vanity reason is `trimmer.io/go-xmp` vs `github.com/trimmer-io/go-xmp` and to avoid lock-in with Github.

**Comment by rubenv** [comment]
While I fully agree that we're all over-depending on Github, the sad fact is that I've seen pretty much every vanity import break at some point. Or disappear after a while.

Either way, thanks for fixing things and for the library!
