### ISSUE TITLE
XMP Sequences are not parsed

### ISSUE THREAD

**Issue by bgreenblatt** [trimmer-io/go-xmp#6]
I am extracting XMP data from PDF files that includes the dc:creator field, which looks like this:

    <dc:creator>
        <rdf:Seq>
            <rdf:li>Mark.Brown</rdf:li>
        </rdf:Seq>
    </dc:creator>

When I create a document and decode it, the creator field isn't present because go-xmp doesn't seem to know about sequences.  Neither Dump() for ListPaths() shows the creator field.

**Comment by bgreenblatt** [comment]
xmp from pdf is:
<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="3.1-701">
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
<rdf:Description rdf:about="" xmlns:pdf="http://ns.adobe.com/pdf/1.3/">
    <pdf:Producer>Nuance PDF Create</pdf:Producer>
</rdf:Description>
<rdf:Description rdf:about="" xmlns:xmp="http://ns.adobe.com/xap/1.0/">
    <xmp:CreatorTool>Microsoft Word - Frontier - 43341-04 - Class 10 Master Ballot (13).docx</xmp:CreatorTool>
    <xmp:CreateDate>2020-07-01T15:30:37-04:00</xmp:CreateDate>
    <xmp:ModifyDate>2020-07-01T15:32:51-04:00</xmp:ModifyDate>
<xmp:MetadataDate>2020-07-01T15:32:51-04:00</xmp:MetadataDate></rdf:Description>
<rdf:Description rdf:about="" xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:format>application/pdf</dc:format>
    <dc:title>
        <rdf:Alt>
            <rdf:li xml:lang="x-default">Microsoft Word - Frontier - 43341-04 - Class 10 Master Ballot (13).docx</rdf:li>
        </rdf:Alt>
    </dc:title>
    <dc:creator>
        <rdf:Seq>
            <rdf:li>Mark.Brown</rdf:li>
        </rdf:Seq>
    </dc:creator>
</rdf:Description>
<rdf:Description rdf:about="" xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/">
    <xmpMM:DocumentID>uuid:5b3195ec-4532-8ed7-1c40-3f1458705844</xmpMM:DocumentID>
    <xmpMM:InstanceID>uuid:8f1fca79-c5fe-8ee4-c7b6-0d256c7f399f</xmpMM:InstanceID>
</rdf:Description>
</rdf:RDF>
</x:xmpmeta>

<?xpacket end="w"?>

output from Dump():
NS EXT http://ns.adobe.com/xap/1.0/ &{Name:xmp URI:http://ns.adobe.com/xap/1.0/ Factory:0x11161e0}
NS EXT http://purl.org/dc/elements/1.1/ &{Name:dc URI:http://purl.org/dc/elements/1.1/ Factory:0x11161e0}
NS EXT http://ns.adobe.com/xap/1.0/mm/ &{Name:xmpMM URI:http://ns.adobe.com/xap/1.0/mm/ Factory:0x11161e0}
NS EXT http://ns.adobe.com/pdf/1.3/ &{Name:pdf URI:http://ns.adobe.com/pdf/1.3/ Factory:0x11161e0}
dc:format = application/pdf
dc:title[x-default] = Microsoft Word - Frontier - 43341-04 - Class 10 Master Ballot (13).docx
pdf:Producer = Nuance PDF Create
xmp:CreateDate = 2020-07-01T15:30:37-04:00
xmp:CreatorTool = Microsoft Word - Frontier - 43341-04 - Class 10 Master Ballot (13).docx
xmp:MetadataDate = 2020-07-01T15:32:51-04:00
xmp:ModifyDate = 2020-07-01T15:32:51-04:00
xmpMM:DocumentID = uuid:5b3195ec-4532-8ed7-1c40-3f1458705844
xmpMM:InstanceID = uuid:8f1fca79-c5fe-8ee4-c7b6-0d256c7f399f

**Comment by echa** [comment]
Hm, `rdf:Seq` are parsed just fine. The XMP you posted contains a few errors (missing `<` and `>`) so it's not legal XML. Could it be that the original is malformed in some way?

When I correct the above XML errors and run `go run cmd/xmpinfo.go -path samples/issue-6-nuance-pdf.xmp` the output looks OK:

```
dc:creator[0] = Mark.Brown
dc:format = application/pdf
dc:title[x-default] = Microsoft Word - Frontier - 43341-04 - Class 10 Master Ballot (13).docx
pdf:Producer = Nuance PDF Create
xmp:CreateDate = 2020-07-01T15:30:37-04:00
xmp:CreatorTool = Microsoft Word - Frontier - 43341-04 - Class 10 Master Ballot (13).docx
xmp:MetadataDate = 2020-07-01T15:32:51-04:00
xmp:ModifyDate = 2020-07-01T15:32:51-04:00
xmpMM:DocumentID = uuid:5b3195ec-4532-8ed7-1c40-3f1458705844
xmpMM:InstanceID = uuid:8f1fca79-c5fe-8ee4-c7b6-0d256c7f399f
```

**Comment by bgreenblatt** [comment]
Thanks so much for taking a look.  This is just output generated from calling the poppler CLI "pdfinfo -meta", and I was never able to get the creator to show up. I just programmatically call pdfinfo and pass the input to create a new Decoder. I didn't get any errors back from the go-xmp calls. What changes to the XMP did you make to get it to work?

**Comment by bgreenblatt** [comment]
Closing the issue. I see the problem.
